# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ThSUComponentData.proto

require 'google/protobuf'

require 'ThTCHGeometry_pb'
require 'ThSUCompDefinitionData_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ThSUComponentData.proto", :syntax => :proto3) do
    add_message "ThSUComponentData" do
      optional :definition, :message, 1, "ThSUCompDefinitionData"
      optional :transformations, :message, 2, "ThTCHMatrix3d"
    end
  end
end

ThSUComponentData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ThSUComponentData").msgclass
