# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ThTCHProjectData.proto

require 'google/protobuf'

require 'ThTCHRootData_pb'
require 'ThTCHSiteData_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ThTCHProjectData.proto", :syntax => :proto3) do
    add_message "ThTCHProjectData" do
      optional :root, :message, 1, "ThTCHRootData"
      optional :site, :message, 2, "ThTCHSiteData"
    end
  end
end

ThTCHProjectData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ThTCHProjectData").msgclass
