# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ThTCHDoorData.proto

require 'google/protobuf'

require_relative 'ThTCHBuiltElementData_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ThTCHDoorData.proto", :syntax => :proto3) do
    add_message "ThTCHDoorData" do
      optional :build_element, :message, 1, "ThTCHBuiltElementData"
    end
  end
end

ThTCHDoorData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ThTCHDoorData").msgclass
