# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ThTCHDoorData.proto

require 'google/protobuf'

require 'ThTCHBuiltElementData_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ThTCHDoorData.proto", :syntax => :proto3) do
    add_message "ThTCHDoorData" do
      optional :build_element, :message, 1, "ThTCHBuiltElementData"
      optional :swing, :enum, 2, "DoorSwing"
      optional :operation, :enum, 3, "DoorTypeOperation"
    end
    add_enum "DoorTypeOperation" do
      value :SWING, 0
      value :SLIDING, 1
    end
    add_enum "DoorSwing" do
      value :SWING_RIGHT_IN, 0
      value :SWING_LEFT_IN, 1
      value :SWING_LEFT_OUT, 2
      value :SWING_RIGHT_OUT, 3
    end
  end
end

ThTCHDoorData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ThTCHDoorData").msgclass
DoorTypeOperation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DoorTypeOperation").enummodule
DoorSwing = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("DoorSwing").enummodule
