# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ThTCHDescendingData.proto

require 'google/protobuf'

require 'ThTCHGeometry_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ThTCHDescendingData.proto", :syntax => :proto3) do
    add_message "ThTCHDescendingData" do
      optional :outline, :message, 1, "ThTCHPolyline"
      optional :is_descending, :bool, 2
      optional :descending_height, :double, 3
      optional :descending_thickness, :double, 4
      optional :descending_wrap_thickness, :double, 5
    end
  end
end

ThTCHDescendingData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ThTCHDescendingData").msgclass
