# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ThTCHBuiltElementData.proto

require 'google/protobuf'

require 'ThTCHRootData_pb'
require 'ThTCHGeometry_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ThTCHBuiltElementData.proto", :syntax => :proto3) do
    add_message "ThTCHBuiltElementData" do
      optional :root, :message, 1, "ThTCHRootData"
      optional :length, :double, 2
      optional :width, :double, 3
      optional :height, :double, 4
      optional :origin, :message, 5, "ThTCHPoint3d"
      optional :x_vector, :message, 6, "ThTCHVector3d"
      proto3_optional :outline, :message, 7, "ThTCHPolyline"
    end
  end
end

ThTCHBuiltElementData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ThTCHBuiltElementData").msgclass
