# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ThTCHBuildingStoreyData.proto

require 'google/protobuf'

require 'ThTCHRootData_pb'
require 'ThTCHWallData_pb'
require 'ThTCHDoorData_pb'
require 'ThTCHWindowData_pb'
require 'ThTCHOpeningData_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ThTCHBuildingStoreyData.proto", :syntax => :proto3) do
    add_message "ThTCHBuildingStoreyData" do
      optional :root, :message, 1, "ThTCHRootData"
      repeated :walls, :message, 2, "ThTCHWallData"
      repeated :doors, :message, 3, "ThTCHDoorData"
      repeated :windows, :message, 4, "ThTCHWindowData"
      repeated :openings, :message, 5, "ThTCHOpeningData"
    end
  end
end

ThTCHBuildingStoreyData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ThTCHBuildingStoreyData").msgclass
