# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProtobufMessage.proto

Sketchup.require 'google/protobuf'

Sketchup.require 'MessageHeader_pb'
Sketchup.require 'ThTCHProjectData_pb'
Sketchup.require 'ThSUProjectData_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ProtobufMessage.proto", :syntax => :proto3) do
    add_message "ProtobufMessage" do
      optional :header, :message, 1, "MessageHeader"
      repeated :cad_projects, :message, 2, "ThTCHProjectData"
      repeated :su_projects, :message, 3, "ThSUProjectData"
    end
  end
end

ProtobufMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ProtobufMessage").msgclass
