# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ThCircleLableGroupData.proto

Sketchup.require 'google/protobuf'

Sketchup.require 'ThTCHRootData_pb'
Sketchup.require 'ThTCHGeometry_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ThCircleLableGroupData.proto", :syntax => :proto3) do
    add_message "CircleLable" do
      optional :root, :message, 1, "ThTCHRootData"
      optional :circle, :message, 2, "ThTCHCircle"
      optional :mark, :string, 3
      repeated :leaders, :message, 4, "ThTCHLine"
    end
    add_message "ThCircleLableGroupData" do
      optional :root, :message, 1, "ThTCHRootData"
      repeated :circle_lables, :message, 2, "CircleLable"
    end
  end
end

CircleLable = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CircleLable").msgclass
ThCircleLableGroupData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ThCircleLableGroupData").msgclass
