# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ThDimensionGroupData.proto

require 'google/protobuf'

require 'ThTCHRootData_pb'
require 'ThTCHGeometry_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ThDimensionGroupData.proto", :syntax => :proto3) do
    add_message "ThAlignedDimension" do
      optional :root, :message, 1, "ThTCHRootData"
      optional :x_line1_point, :message, 2, "ThTCHPoint3d"
      optional :x_line2_point, :message, 3, "ThTCHPoint3d"
      optional :dim_line_point, :message, 4, "ThTCHPoint3d"
      optional :mark, :string, 5
    end
    add_message "ThDimensionGroupData" do
      optional :root, :message, 1, "ThTCHRootData"
      repeated :dimensions, :message, 2, "ThAlignedDimension"
    end
  end
end

ThAlignedDimension = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ThAlignedDimension").msgclass
ThDimensionGroupData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ThDimensionGroupData").msgclass
