# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ThGridLineSyetemData.proto

Sketchup.require 'google/protobuf'

Sketchup.require 'ThTCHRootData_pb'
Sketchup.require 'ThTCHGeometry_pb'
Sketchup.require 'ThCircleLableGroupData_pb'
Sketchup.require 'ThDimensionGroupData_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ThGridLineSyetemData.proto", :syntax => :proto3) do
    add_message "ThGridLineSyetemData" do
      optional :root, :message, 1, "ThTCHRootData"
      repeated :grid_lines, :message, 2, "ThTCHPolyline"
      repeated :circle_lable_groups, :message, 3, "ThCircleLableGroupData"
      repeated :dimension_groups, :message, 4, "ThDimensionGroupData"
    end
  end
end

ThGridLineSyetemData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ThGridLineSyetemData").msgclass
