# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ThSUBuildingElementData.proto

require 'google/protobuf'

require 'ThTCHRootData_pb'
require 'ThSUComponentData_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ThSUBuildingElementData.proto", :syntax => :proto3) do
    add_message "ThSUBuildingElementData" do
      optional :root, :message, 1, "ThTCHRootData"
      optional :component, :message, 2, "ThSUComponentData"
    end
  end
end

ThSUBuildingElementData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ThSUBuildingElementData").msgclass
