# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ThSUCompDefinitionData.proto

require 'google/protobuf'

require 'ThSUFaceData_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ThSUCompDefinitionData.proto", :syntax => :proto3) do
    add_message "ThSUCompDefinitionData" do
      optional :definition_name, :string, 1
      optional :ifc_classification, :string, 2
      repeated :faces, :message, 3, "ThSUFaceData"
    end
  end
end

ThSUCompDefinitionData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ThSUCompDefinitionData").msgclass
