# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ThSUFollowSlopeElementData.proto

require 'google/protobuf'

require 'ThSUComponentData_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ThSUFollowSlopeElementData.proto", :syntax => :proto3) do
    add_message "ThSUFollowSlopeElementData" do
      optional :component, :message, 1, "ThSUComponentData"
    end
  end
end

ThSUFollowSlopeElementData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ThSUFollowSlopeElementData").msgclass
