# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ThSUGeometry.proto

Sketchup.require 'google/protobuf'

Sketchup.require 'ThTCHGeometry_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ThSUGeometry.proto", :syntax => :proto3) do
    add_message "ThSUPolygon" do
      repeated :indices, :int32, 1
    end
    add_message "ThSUPolygonMesh" do
      repeated :points, :message, 1, "ThTCHPoint3d"
      repeated :polygons, :message, 2, "ThSUPolygon"
    end
  end
end

ThSUPolygon = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ThSUPolygon").msgclass
ThSUPolygonMesh = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ThSUPolygonMesh").msgclass
