# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ThSUMaterialData.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ThSUMaterialData.proto", :syntax => :proto3) do
    add_message "ThSUMaterialData" do
      optional :material_name, :string, 1
      optional :alpha, :float, 2
      optional :hasRGB, :bool, 3
      proto3_optional :color_r, :int32, 4
      proto3_optional :color_g, :int32, 5
      proto3_optional :color_b, :int32, 6
    end
  end
end

ThSUMaterialData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ThSUMaterialData").msgclass
