# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ThSUFollowSlopeRooofData.proto

Sketchup.require 'google/protobuf'

Sketchup.require 'ThSUCompDefinitionData_pb'
Sketchup.require 'ThSUFollowSlopeElementData_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ThSUFollowSlopeRooofData.proto", :syntax => :proto3) do
    add_message "ThSUFollowSlopeRooofData" do
      optional :globalId, :string, 1
      repeated :elements, :message, 2, "ThSUFollowSlopeElementData"
      repeated :definitions, :message, 3, "ThSUCompDefinitionData"
    end
  end
end

ThSUFollowSlopeRooofData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ThSUFollowSlopeRooofData").msgclass
