# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ThSUProjectData.proto

Sketchup.require 'google/protobuf'

Sketchup.require 'ThTCHRootData_pb'
Sketchup.require 'ThSUCompDefinitionData_pb'
Sketchup.require 'ThSUBuildingData_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ThSUProjectData.proto", :syntax => :proto3) do
    add_message "ThSUProjectData" do
      optional :root, :message, 1, "ThTCHRootData"
      repeated :definitions, :message, 2, "ThSUCompDefinitionData"
      optional :building, :message, 3, "ThSUBuildingData"
      optional :is_face_mesh, :bool, 4
      optional :project_path, :string, 5
      optional :project_id, :string, 6
      optional :project_sub_id, :string, 7
      optional :binding_name, :string, 8
    end
  end
end

ThSUProjectData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ThSUProjectData").msgclass
