# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ThSUCompDefinitionData.proto

require 'google/protobuf'

require 'ThSUFaceBrepData_pb'
require 'ThSUFaceMeshData_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ThSUCompDefinitionData.proto", :syntax => :proto3) do
    add_message "ThSUCompDefinitionData" do
      optional :definition_name, :string, 1
      optional :ifc_classification, :string, 2
      optional :instance_name, :string, 3
      repeated :brep_faces, :message, 4, "ThSUFaceBrepData"
      repeated :mesh_faces, :message, 5, "ThSUFaceMeshData"
    end
  end
end

ThSUCompDefinitionData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ThSUCompDefinitionData").msgclass
