# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ThSUCompDefinitionData.proto

Sketchup.require 'google/protobuf'

Sketchup.require 'ThSUFaceBrepData_pb'
Sketchup.require 'ThSUFaceMeshData_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ThSUCompDefinitionData.proto", :syntax => :proto3) do
    add_message "ThSUCompDefinitionData" do
      optional :definition_name, :string, 1
      repeated :brep_faces, :message, 2, "ThSUFaceBrepData"
      repeated :mesh_faces, :message, 3, "ThSUFaceMeshData"
    end
  end
end

ThSUCompDefinitionData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ThSUCompDefinitionData").msgclass
