# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ThSUFaceMeshData.proto

require 'google/protobuf'

require 'ThSUGeometry_pb'
require 'ThTCHGeometry_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ThSUFaceMeshData.proto", :syntax => :proto3) do
    add_message "ThSUFaceMeshData" do
      optional :mesh, :message, 1, "ThSUPolygonMesh"
      optional :face_normal, :message, 2, "ThTCHVector3d"
    end
  end
end

ThSUFaceMeshData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ThSUFaceMeshData").msgclass
