# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ThTCHSiteData.proto

require 'google/protobuf'

require 'ThTCHRootData_pb'
require 'ThTCHBuildingData_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ThTCHSiteData.proto", :syntax => :proto3) do
    add_message "ThTCHSiteData" do
      optional :root, :message, 1, "ThTCHRootData"
      repeated :buildings, :message, 2, "ThTCHBuildingData"
    end
  end
end

ThTCHSiteData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ThTCHSiteData").msgclass
