# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ThTCHGridAxisData.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ThTCHGridAxisData.proto", :syntax => :proto3) do
    add_message "ThTCHGridAxisData" do
    end
  end
end

ThTCHGridAxisData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ThTCHGridAxisData").msgclass
