# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ThTCHPositioningElementData.proto

Sketchup.require 'google/protobuf'

Sketchup.require 'ThTCHRootData_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ThTCHPositioningElementData.proto", :syntax => :proto3) do
    add_message "ThTCHPositioningElementData" do
      optional :root, :message, 1, "ThTCHRootData"
    end
  end
end

ThTCHPositioningElementData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ThTCHPositioningElementData").msgclass
