# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ThTCHProperty.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ThTCHProperty.proto", :syntax => :proto3) do
    add_message "ThTCHProperty" do
      optional :key, :string, 1
      optional :value, :string, 2
    end
  end
end

ThTCHProperty = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ThTCHProperty").msgclass
