# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ThTCHBuildingData.proto

Sketchup.require 'google/protobuf'

Sketchup.require 'ThTCHRootData_pb'
Sketchup.require 'ThTCHBuildingStoreyData_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ThTCHBuildingData.proto", :syntax => :proto3) do
    add_message "ThTCHBuildingData" do
      optional :root, :message, 1, "ThTCHRootData"
      repeated :storeys, :message, 2, "ThTCHBuildingStoreyData"
    end
  end
end

ThTCHBuildingData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ThTCHBuildingData").msgclass
