# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ThTCHRoomData.proto

require 'google/protobuf'

require 'ThTCHBuiltElementData_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ThTCHRoomData.proto", :syntax => :proto3) do
    add_message "ThTCHRoomData" do
      optional :build_element, :message, 1, "ThTCHBuiltElementData"
    end
  end
end

ThTCHRoomData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ThTCHRoomData").msgclass
