# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ThTCHGeometry.proto

Sketchup.require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ThTCHGeometry.proto", :syntax => :proto3) do
    add_message "ThTCHPoint3d" do
      optional :x, :double, 1
      optional :y, :double, 2
      optional :z, :double, 3
    end
    add_message "ThTCHVector3d" do
      optional :x, :double, 1
      optional :y, :double, 2
      optional :z, :double, 3
    end
    add_message "ThTCHMatrix3d" do
      optional :data11, :double, 1
      optional :data12, :double, 2
      optional :data13, :double, 3
      optional :data14, :double, 4
      optional :data21, :double, 5
      optional :data22, :double, 6
      optional :data23, :double, 7
      optional :data24, :double, 8
      optional :data31, :double, 9
      optional :data32, :double, 10
      optional :data33, :double, 11
      optional :data34, :double, 12
      optional :data41, :double, 13
      optional :data42, :double, 14
      optional :data43, :double, 15
      optional :data44, :double, 16
    end
    add_message "ThTCHSegment" do
      repeated :index, :uint32, 1
    end
    add_message "ThTCHCircle" do
      optional :center, :message, 1, "ThTCHPoint3d"
      optional :radius, :double, 2
    end
    add_message "ThTCHLine" do
      optional :start_pt, :message, 1, "ThTCHPoint3d"
      optional :end_pt, :message, 2, "ThTCHPoint3d"
    end
    add_message "ThTCHPolyline" do
      optional :is_closed, :bool, 1
      repeated :points, :message, 2, "ThTCHPoint3d"
      repeated :segments, :message, 3, "ThTCHSegment"
    end
    add_message "ThTCHMPolygon" do
      optional :shell, :message, 1, "ThTCHPolyline"
      repeated :holes, :message, 2, "ThTCHPolyline"
    end
  end
end

ThTCHPoint3d = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ThTCHPoint3d").msgclass
ThTCHVector3d = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ThTCHVector3d").msgclass
ThTCHMatrix3d = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ThTCHMatrix3d").msgclass
ThTCHSegment = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ThTCHSegment").msgclass
ThTCHCircle = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ThTCHCircle").msgclass
ThTCHLine = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ThTCHLine").msgclass
ThTCHPolyline = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ThTCHPolyline").msgclass
ThTCHMPolygon = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ThTCHMPolygon").msgclass
