# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ThTCHBuildingStoreyData.proto

require 'google/protobuf'

require 'ThTCHBuiltElementData_pb'
require 'ThTCHWallData_pb'
require 'ThTCHDoorData_pb'
require 'ThTCHGeometry_pb'
require 'ThTCHWindowData_pb'
require 'ThTCHSlabData_pb'
require 'ThTCHRailingData_pb'
require 'ThTCHOpeningData_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ThTCHBuildingStoreyData.proto", :syntax => :proto3) do
    add_message "ThTCHBuildingStoreyData" do
      optional :build_element, :message, 1, "ThTCHBuiltElementData"
      optional :number, :string, 2
      optional :height, :double, 3
      optional :elevation, :double, 4
      optional :usage, :string, 5
      optional :origin, :message, 6, "ThTCHPoint3d"
      optional :memory_storey_id, :string, 7
      optional :memory_matrix3d, :message, 8, "ThTCHMatrix3d"
      repeated :walls, :message, 9, "ThTCHWallData"
      repeated :doors, :message, 10, "ThTCHDoorData"
      repeated :windows, :message, 11, "ThTCHWindowData"
      repeated :slabs, :message, 12, "ThTCHSlabData"
      repeated :railings, :message, 13, "ThTCHRailingData"
    end
  end
end

ThTCHBuildingStoreyData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ThTCHBuildingStoreyData").msgclass
