# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ThTCHProjectData.proto

Sketchup.require 'google/protobuf'

Sketchup.require 'ThTCHRootData_pb'
Sketchup.require 'ThTCHSiteData_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ThTCHProjectData.proto", :syntax => :proto3) do
    add_message "ThTCHProjectData" do
      optional :root, :message, 1, "ThTCHRootData"
      repeated :sites, :message, 2, "ThTCHSiteData"
      optional :project_id, :string, 3
      optional :project_sub_id, :string, 4
      optional :project_path, :string, 5
      optional :binding_name, :string, 6
    end
  end
end

ThTCHProjectData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ThTCHProjectData").msgclass
